"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Koa = require("koa");
var router_1 = require("./app/router");
var bodyParser = require("koa-bodyparser");
var app = new Koa();
app.use(bodyParser());
app.use(router_1.default.routes());
app.use(router_1.default.allowedMethods());
var server = app.listen(3000);
exports.default = server;
